version: '3'
services:
  mysql:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data/mysql:/var/lib/mysql
    expose:
      - 3306
    ports:
      - "3306:3306"
     
  flask:
    build: flask
    container_name: flask
    volumes:
      - ./data/app:/code
    depends_on:
      - mysql
    ports:
      - "5000:5000"
 